CREATE DATABASE IF NOT EXISTS rag_standards CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'rag'@'%' IDENTIFIED BY 'rag123456';
GRANT ALL PRIVILEGES ON rag_standards.* TO 'rag'@'%';
FLUSH PRIVILEGES;
